// 200 common 5-letter words for the game
const WORD_LIST = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
  "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
  "alike", "alive", "alley", "allow", "alone", "along", "alter", "angel",
  "anger", "angle", "angry", "anime", "ankle", "annex", "antic", "anvil",
  "apart", "apple", "apply", "arena", "argue", "arise", "armor", "arrow",
  "arson", "aside", "asked", "asset", "atlas", "avoid", "award", "aware",
  "awful", "basic", "basis", "batch", "beach", "beard", "beast", "began",
  "begin", "being", "below", "bench", "billy", "black", "blade", "blame",
  "bland", "blast", "blaze", "bleed", "bless", "blind", "block", "blood",
  "bloom", "blown", "blues", "blunt", "board", "boast", "bonus", "boost",
  "booth", "bound", "brain", "brand", "brave", "bread", "break", "breed",
  "bribe", "bride", "brief", "bring", "broad", "broke", "brook", "broom",
  "broth", "brown", "brush", "build", "built", "burst", "cabin", "camel",
  "candy", "carry", "cause", "cease", "chain", "chair", "chalk", "chaos",
  "charm", "chart", "chase", "cheap", "check", "cheek", "cheer", "chess",
  "chest", "chief", "child", "choir", "civic", "civil", "claim", "clash",
  "class", "clean", "clear", "clerk", "click", "cliff", "climb", "cling",
  "clock", "clone", "close", "cloth", "cloud", "clown", "coach", "coast",
  "cobra", "combo", "comic", "coral", "corps", "count", "court", "cover",
  "craft", "crane", "crash", "crazy", "cream", "creek", "crime", "crisp",
  "cross", "crowd", "crown", "cruel", "crush", "curve", "cycle", "daily",
  "dance", "datum", "debut", "decoy", "delay", "delta", "dense", "depot",
  "depth", "derby", "devil", "digit", "disco", "ditch", "dizzy", "dodge",
  "dolly", "donor", "doubt", "dough", "draft", "drain", "drake", "drama",
  "drank", "drawl", "dream", "dress", "drift", "drink", "drive", "drone",
  "drown", "druid", "drunk", "dryer", "duchy", "dully", "dwarf", "dying",
];

const SECRET_WORDS = [
  "about", "actor", "acute", "agent", "alarm", "alert", "alike", "alive",
  "angel", "angry", "ankle", "apart", "apple", "apply", "argue", "arise",
  "aside", "atlas", "avoid", "award", "aware", "basic", "beach", "beard",
  "beast", "begin", "below", "bench", "black", "blade", "blame", "blast",
  "blaze", "bleed", "bless", "blind", "block", "blood", "bloom", "blown",
  "board", "bonus", "boost", "brain", "brand", "brave", "bread", "break",
  "breed", "bride", "brief", "bring", "broad", "broke", "broom", "brown",
  "brush", "build", "burst", "cabin", "candy", "carry", "cause", "chain",
  "chair", "chaos", "charm", "chart", "chase", "cheap", "check", "cheer",
  "chest", "child", "claim", "clash", "class", "clean", "clear", "click",
  "cliff", "climb", "clock", "close", "cloud", "coach", "coast", "count",
  "court", "cover", "craft", "crane", "crash", "crazy", "cream", "crime",
  "cross", "crowd", "crown", "crush", "curve", "cycle", "dance", "debut",
  "delay", "dense", "depth", "devil", "disco", "dizzy", "doubt", "draft",
  "drain", "drama", "dream", "dress", "drift", "drink", "drive", "drone",
];

module.exports = { WORD_LIST, SECRET_WORDS };
